openapi: 3.0.0
paths:
  /transactions:
    post:
      summary: Create a new transaction
      tags:
        - Transactions
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                amount:
                  type: number
                  description: The amount to be transferred
                  example: 1000
                sender_account_id:
                  type: string
                  description: The ID of the sender's account
                  example: "12345"
                receiver_account_id:
                  type: string
                  description: The ID of the receiver's account
                  example: "67890"
                description:
                  type: string
                  description: Description of the transaction
                  example: "Payment for services"
                transfer_purpose:
                  type: string
                  description: The purpose of the transfer
                  example: "Business"
      responses:
        201:
          description: Transaction created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: "SUCCESS"
                  data:
                    type: object
                    properties:
                      transaction:
                        type: object
                        description: Details of the created transaction
                        example:
                          id: "abc123"
                          amount: 1000
                          date: "2024-08-12T12:00:00.000Z"
                          sender_account_id: "12345"
                          receiver_account_id: "67890"
                          description: "Payment for services"
                          transfer_purpose: "Business"
        400:
          description: Bad request - Invalid input data
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: "ERROR"
                  message:
                    type: string
                    example: "Please provide all required details"
        500:
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: "ERROR"
                  message:
                    type: string
                    example: "Internal server error"
                    
    get:
      summary: Get all transactions
      tags:
        - Transactions
      responses:
        200:
          description: List of all transactions
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: "SUCCESS"
                  data:
                    type: object
                    properties:
                      transactions:
                        type: array
                        items:
                          type: object
                          description: Details of each transaction
                          example:
                            id: "abc123"
                            amount: 1000
                            date: "2024-08-12T12:00:00.000Z"
                            sender_account_id: "12345"
                            receiver_account_id: "67890"
                            description: "Payment for services"
                            transfer_purpose: "Business"
        500:
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: "ERROR"
                  message:
                    type: string
                    example: "Internal server error"

  /transactions/{id}:
    get:
      summary: Get details of a specific transaction
      tags:
        - Transactions
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            example: "abc123"
          description: The ID of the transaction
      responses:
        200:
          description: Details of the specific transaction
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: "SUCCESS"
                  data:
                    type: object
                    properties:
                      transaction:
                        type: object
                        description: Details of the transaction
                        example:
                          id: "abc123"
                          amount: 1000
                          date: "2024-08-12T12:00:00.000Z"
                          sender_account_id: "12345"
                          receiver_account_id: "67890"
                          description: "Payment for services"
                          transfer_purpose: "Business"
                      senderAccount:
                        type: object
                        description: Sender's account details
                        example:
                          accountNumber: "1234567890"
                          balance: 5000
                          bankName: "BCA"
                      receiverAccount:
                        type: object
                        description: Receiver's account details
                        example:
                          accountNumber: "0987654321"
                          balance: 1000
                          bankName: "Mandiri"
        400:
          description: Bad request - Invalid transaction ID
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: "ERROR"
                  message:
                    type: string
                    example: "Please provide transaction id"
        404:
          description: Transaction not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: "ERROR"
                  message:
                    type: string
                    example: "Transaction not found"
        500:
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: "ERROR"
                  message:
                    type: string
                    example: "Internal server error"
